import {
    REFERENCES,
    FIREBASE_IO_INSTANCE_KEY,
    LOBBY_SESSION_INSTANCE_KEY,
    PAGE_MANAGER_INSTANCE_KEY
} from "../core/ReferenceStorage.mjs";
import Utils from "../core/Utils.mjs";
/*****************************************************************
 * LobbySession.mjs
 * @author MacSmith22115
 * Created: Term #1 2026
 * Description: 
 *      -> Contains Fields and Methods relating to an instance of a lobby
 *      -> Uses Firebase to mediate and store Lobbies
 *      -> Contains cache of the lobby, generated by reading Firebase.
 ****************************************************************/
export default class LobbySession {
    #cache = {};
    #lobbyId;
    #state;
    #firebaseListeners;

    /*****************************************************************
    * Description:
    *   -> Writes the lobby to the database
    * Params: 
    *   -> '_callback': Function to be called after a sucessful lobby creation
    *****************************************************************/
    async createLobby(_callback = null) {
        const LOBBY_UUID = crypto.randomUUID();
        const FBIO = REFERENCES[FIREBASE_IO_INSTANCE_KEY];
        const PLAYER_UID = FBIO.authedUser().uid;
        await FBIO.update(`lobbies`, {
            [LOBBY_UUID]: {
                players: [PLAYER_UID],
                flags: {
                    gameStarted: false,
                    lobbyOpen: true
                }
            }
        }, async () => {
            this.#lobbyId = LOBBY_UUID;
            await this.generateCache();
            REFERENCES[LOBBY_SESSION_INSTANCE_KEY] = this;
            if (_callback) _callback();
            const PLAYER_LIST = Object.values(this.getLobbyCache().players);
            const INDEX = PLAYER_LIST.indexOf(PLAYER_UID);
            await FBIO.onClientDisconnect(`lobbies/${this.getLobbyId()}/players/${INDEX}`)
        });
    }


    /*****************************************************************
    * Description:
    *   -> Joins the user to an existing lobby
    * Params: 
    *   -> '_id': Id of lobby to join
    *   -> '_callback': Function to be called after a sucessful lobby joining
    *****************************************************************/
    async joinLobby(_id, _callback = null) {
        const FBIO = REFERENCES[FIREBASE_IO_INSTANCE_KEY];
        const LOBBY = await FBIO.read(`lobbies/${_id}`);
        const PLAYER_UID = FBIO.authedUser().uid;
        if (LOBBY != null) {
            const PLAYERS = LOBBY.players != null ? Object.values(LOBBY.players) : [];
            PLAYERS.push(PLAYER_UID);
            await FBIO.update(`lobbies/${_id}`, {
                players: PLAYERS
            }, async () => {
                this.#lobbyId = _id;
                await this.generateCache();
                REFERENCES[LOBBY_SESSION_INSTANCE_KEY] = this;
                if (_callback) _callback();
                const PLAYER_LIST = Object.values(this.getLobbyCache().players);
                const INDEX = PLAYER_LIST.indexOf(PLAYER_UID);
                await FBIO.onClientDisconnect(`lobbies/${this.getLobbyId()}/players/${INDEX}`)
            })
        }
    }


    /*****************************************************************
    * Description:
    *   -> Removes the lobby from Firebase
    *****************************************************************/
    async closeLobby() {
        const FBIO = REFERENCES[FIREBASE_IO_INSTANCE_KEY];
        FBIO.remove(`lobbies/${this.getLobbyId()}`);
    }


    /*****************************************************************
    * Description:
    *   -> Reads the data for the current hearts trick and returns it, or {} if null
    *****************************************************************/
    async getTrickData() {
        const FBIO = REFERENCES[FIREBASE_IO_INSTANCE_KEY];
        const LOBBY = await FBIO.read(`lobbies/${this.getLobbyId()}`);
        return LOBBY.trickData ?? {};
    }


    /*****************************************************************
    * Description:
    *   -> Returns all players current points from cache
    * Params: 
    *   -> '_sorted': Wether the points should be sorted, with lower points being first
    *****************************************************************/
    async getPoints(_sorted = false) {
        const FBIO = REFERENCES[FIREBASE_IO_INSTANCE_KEY];
        let points = this.getLobbyCache().points ?? {};
        if (_sorted) {
            if (!Utils.isObjEmpty(points)) {
                points = Object.entries(points).map(([player, score]) => ({ player, score }));
                points = Utils.sortObjsAscending(points, 'score');
            }
        }
        return points;
    }


    /*****************************************************************
    * Description:
    *   -> Writes to the database the 'roundOver' flag as true
    * Params: 
    *   -> '_fbio': Instance of FirebaseIO.mjs
    *****************************************************************/
    async markRoundOver(_fbio) {
        await this.getLobbyCache();
        await REFERENCES[PAGE_MANAGER_INSTANCE_KEY].getMainPage().writeRoundOver();
        await _fbio.update(`lobbies/${this.getLobbyId()}/flags`, {
            roundOver: true
        })
    }


    /*****************************************************************
    * Description:
    *   -> Checks if it it currently the client's turn
    *****************************************************************/
    isMyTurn() {
        return this.getLobbyCache().turn == REFERENCES[FIREBASE_IO_INSTANCE_KEY].authedUser().uid;
    }


    /*****************************************************************
    * Description:
    *   -> Reads the entire lobby path, and caches it for quicker acess later
    *****************************************************************/
    async generateCache() {
        if (this.#lobbyId != null) {
            this.#cache.lobby = await REFERENCES[FIREBASE_IO_INSTANCE_KEY].read(`lobbies/${this.#lobbyId}`);
        }
    }


    /*****************************************************************
    * Description:
    *   -> Gets cached lobby data
    *****************************************************************/
    getLobbyCache() {
        return this.#cache.lobby;
    }


    /*****************************************************************
    * Description:
    *   -> Gets the ID of the lobby
    *****************************************************************/
    getLobbyId() {
        return this.#lobbyId;
    }


    /*****************************************************************
    * Description:
    *   -> Writes to the database things required for a new round of Hearts
    *****************************************************************/
    resetRound() {
        const FBIO = REFERENCES[FIREBASE_IO_INSTANCE_KEY];
        const LOBBY = this;
        const CACHE = LOBBY.getLobbyCache();

        const FLAGS = CACHE.flags ?? {};
        for (const [_flag, _val] of Object.entries(FLAGS)) {
            switch (_flag) {
                case 'roundOver':
                    FLAGS.roundOver = false;
                    break;
            }
        }
    }
}